#!/bin/bash

# Created January 14th
# Script to submit multiple jobs for mpi runs for ogs
# projectname of job on eve is equvalent to projectname+folder

read -p 'Number of slots: ' number_of_slots
set -e

# set home and working directory
dir_home='/home/houben'
dir_work='/work/houben'
projectname='transect'
# set prejectname
CWD="$(pwd)"

# loop over all directories and subdirectories and submit a relating job
for directories in */ ; do
name_dir=$directories
dir_sim=$CWD/$name_dir

### SoftLinks to OGS-Unix-Executable ###
ln -sf /home/houben/OGS_mpi_own/ogs5/build/bin/ogs ${dir_sim}ogs


### Neuschreiben des qsub-Skripts ###

submitfile=${dir_sim}qsub_${name_dir%?}.sh
	cat > ${submitfile} << EOF
#!/bin/bash
#$ -S /bin/bash
#$ -N ${projectname}${directories%?}
#$ -l h_rt=86400
#$ -l h_vmem=4G

# output files will be merged to one single file
#$ -o ${dir_sim}${name_dir%?}_ogs.log
#$ -j y	

#$ -pe openmpi-orte $number_of_slots

module load openmpi/gcc/1.8.8-1
mpirun -np $number_of_slots ${dir_sim}ogs ${dir_sim}${projectname}
EOF

qsub ${submitfile}
echo 'Your job should be in progress! Name of directory:'
echo ${dir_sim}


done
